obj-$(CONFIG_LUSTREFSX_LNET_EFALND)	+= kefalnd.o

kefalnd-y		:= efalnd.o efalnd_connection.o efalnd_modparams.o efalnd_peerni.o efalnd_debugfs.o

include $(srctree)/drivers/staging/lustrefsx/Makefile.rules
