#ifndef _ENA_CONFIG_H_
#define _ENA_CONFIG_H_
#define ENA_HAVE_PCI_DEV_ID 1
#define ENA_HAVE_XDP_DO_FLUSH 1
#define ENA_HAVE_CPUMASK_LOCAL_SPREAD 1
#define ENA_HAVE_UPDATE_AFFINITY_HINT 1
#define ENA_HAVE_ETHTOOL_OPS_SUPPORTED_COALESCE_PARAMS 1
#define ENA_HAVE_ETH_HW_ADDR_SET 1
#define ENA_NAPI_ALLOC_SKB_EXPLICIT_GFP_MASK 1
#define ENA_ETHTOOL_NFC_IPV6_SUPPORTED 1
#endif /* _ENA_CONFIG_H_ */
